<body>	
	<aside id="face">
	  <div id="face">
		<!--facebook-->
        <iframe class="iframe" src="https://www.facebook.com/plugins/like.php?href=http://www.facebook.com%3A%2F%2FIncahuasiLambayeque%2F&width=75&layout=box_count&action=like&show_faces=true&share=true&height=65&appId" width="75" height="65" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
      </div>
	</aside>
	
	<section id="cuerpo">    


	  <section id="fotos_1">
		<div class="flexslider">
			<ul class="slides">
				<li>
				  <img src="inca1.jpg" alt="">
				  <p class="flex-caption">Distrito de Incahuasi</p>
				</li>
				<li>
				  <img src="inca2.jpg" alt="">
				</li>
				<li>
				  <img src="totoras.jpg" alt="">
				</li>
				<li>
				  <img src="uyurp.jpg" alt="">
				</li>
				<li>
				  <img src="inca3.JPG" alt="">
				</li>
				<li>
				  <img src="totoras1.jpg" alt="">
				</li>
				<li>
				  <img src="inca4.jpg" alt="">
				</li>
				<li>
				  <img src="totoras3.jpg" alt="">
				</li>
			</ul>
		</div>
	 
		<div id="himno">
			<img id="himno" src="HIMNO.jpg" alt="">
			<audio controls>
				<source src="himno_incahuasi.MP3" type="audio/mp3">
			</audio>
		</div>
	  </section>
	  <section class="video">
        <div id="centros_poblados">
	         <h1 id="tranca">La Tranca</h1>
	  	     <embed src="latranca_1.jpg" type=""></embed>
	  	     <p></p>

	  	</div>

        <div id="links_1">
       <h1 id="link_cp">Centros Poblados</h1>
      	<nav id="links">
      		<ul>
      			<li class="uno"><a href="#tranca">La Tranca</a></li>
      		</ul>
      		<ul>
      			<li class="dos"><a href="#uyurpampa">Uyurpampa</a></li>
      		</ul>
      		<ul>
      			<li class="uno"><a href="#camchachala">Canchachalá</a></li>
      		</ul>
      		<ul>
      			<li class="dos"><a href="#">Moyán</a></li>
      		</ul>
      		<ul>
      			<li class="uno"><a href="#">Janque</a></li>
      		</ul>
      		<ul>
      			<li class="dos"><a href="#">Congacha</a></li>
      		</ul>
      		<ul>
      			<li class="uno"><a href="#">La Tranca</a></li>
      		</ul>
      	</nav>
      	<h2 id="link_video">Videos</h2>
      	<nav id="links">
      		<ul>
      			<li class="uno"><a href="#video">Videos - Takin</a></li>
      		</ul>
      	</nav>
      </div>
        <img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1 id="uyurpampa">Uyurpampa</h1>
	  	     <img src="uyurpampa01.jpg" type=""></img>
	  	     <p></p>
	  	</div>
	  	<img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1 id="camchachala">Canchachalá</h1>
	  	     <img src="camchachala.jpg" type=""></img>
	  	     <p></p>
	  	</div>
	  	<img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1 id="moyan">Moyán</h1>
	  	     <img src="moyan01.jpg" type=""></img>
	  	     <p></p>
	  	</div>
	  	<img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1 id="janque">Janque</h1>
	  	     <img src="janque01.jpg" type=""></img>
	  	     <p></p>
	  	</div>
	  	<img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1 id="congacha">Congacha</h1>
	  	     <img src="congacha01.jpg" type=""></img>
	  	     <p></p>
	  	</div>
	  	<img id="linea" src="inca113.png" type=""></img>
	  	<div id="centros_poblados">
	         <h1>Uyurpampa</h1>
	  	     <img src="latranca_1.jpg" type=""></img>
	  	     <p></p>
	  	</div>

	  	  <iframe id="video" width="560" height="315" src="https://www.youtube.com/embed/w2wHyJU_ddY" frameborder="0" allowfullscreen></iframe>
	  	  <iframe id="video" width="560" height="315" src="https://www.youtube.com/embed/T3qR4JOIkVc" frameborder="0" allowfullscreen></iframe>
	  </section>
	  <article class="comentarios">
	  	<div class="fb-comments" data-href="https://incahuasi.herokuapp.com/index.php" data-width="60%" data-numposts="3"></div>                	
       </div>
      </article>
	</section>
	
	</html>
